Google:
  Cloud:
    # Google Cloud Service credentials
    credentials_file_name: isw-personal-scripts-314a6167bf08.json

  Sheets:
    # Our Finances
    spreadsheet_key: 1Sj13auBheoZalYbs1KUe1ESf0Gq-3gD2DfjdFmVEPTc
    # Use spreadsheet_name to check validity of spreadsheet_key
    spreadsheet_name: Our Finances
    convert_underscore_tables: false

Output:
  directory: output

SQLite:
  database_name: our_finances.sqlite

