# null values indicate real values are expected to be set in the environment

CONVERT_ACCOUNT_TABLES: true

# Path to the service account key file for Google APIs.
GOOGLE_SERVICE_ACCOUNT_KEY_FILE: null

OUR_FINANCES_KEY: null

OUTPUT_DIRECTORY: output

SQLALCHEMY_ECHO: false


#  database_url: sqlite:///our_finances.sqlite
  
# SQLite:  database_name: our_finances.sqlite

