from cls_table_categories import Categories
from cls_table_hmrc_people_details import HMRC_PeopleDetails
from cls_table_hmrc_questions_by_year import HMRC_QuestionsByYear
from cls_table_people import People
from cls_table_transactions import Transactions
